### PR TITLE
Fix/line wrapping

### PR DESCRIPTION
**Pull request by DaazKu**
Line wrapping was extended to the first line of the description.

### CODE REVIEW

**Comment by tburry** [comment]
Can you add a unit test?

**Comment by tburry** [comment]
PHPUnit has a method called **expectOutputString()** that might do this better.

**Comment by tburry** [comment]
Now that I'm looking at the PR I don't quite get what you're doing here. It seems like you are removing wrapping if `formatOutput` is false which isn't correct. That property only refers to terminal code formatting. What, specifically are you trying to do here?

**Comment by DaazKu** [comment]
$wrap is only used if $this->formatOutput is true.

**Comment by tburry** [comment]
You didn't answer my question.

**Comment by DaazKu** [comment]
The PR fix a bug where the formatting would be applied on the wrong column.
Currently, the first line of a description is also wrapped in bold if the option is required.
This is because `$i` is used instead of `$j`.

To answer your question specifically, I am not removing wrapping if formatOutput is false.
The code was:
```
//This is defining wrapping
if(isset($row[$j])) {
    $wrap = $row[$j][1];
} else {
    // if we're out of array, use the latest wraps
    $wrap = $row[count($row)-1][1];
}

if ($this->formatOutput) {
    //This is applying wrapping
    echo str_repeat(' ', $padding).$wrap[0].$lines[$i].$wrap[1];
} else {
    echo str_repeat(' ', $padding).$lines[$i];
}
```

I just moved the definition in that if statement since it is not used anywhere else.

**Pull request merged**
